pipeline {
    agent any
    environment {
        DOCKER_IMAGE_NAME = "karimfadl/bulletin-board"
    }
    stages {
        stage('Build Docker Image') {
            when {
                branch 'main'
            }
            steps {
                script {
                    app = docker.build("DOCKER_IMAGE_NAME", "./bulletin-board-app/Dockerfile") 
                    app.inside {
                        sh 'echo Hello, Node Bulletin Board App!'
                    }
                }
            }
        }
        stage('Push Docker Image') {
            when {
                branch 'main'
            }
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker_hub_login') {
                        app.push("${env.BUILD_NUMBER}")
                        app.push("latest")
                    }
                }
            }
        }


        stage('DeployToProduction') {
            when {
                branch 'main'
            }
            steps {
                input 'Deploy to Production?'
                milestone(1)
                kubernetesDeploy(
                    kubeconfigId: 'kubeconfig',
                    configs: '../k8s-bulletin-board/app-bulletin-board.yaml',
                    enableConfigSubstitution: true
                )
            }
        }
    }
}
