---
- name: Create A New Account on Dell Server and Install Tomcat
  hosts: dell_server
  user: karim
  become: yes
  connection: ssh
  vars:
   ansible_become_pass: dellemc
   ansible_ssh_port: 22
  roles:
   - System
   - Tomcat 
