pipeline {
    agent any
    environment {
        DOCKER_IMAGE_NAME = "karimfadl/bulletin-board"
    }
    stages {
        stage('Build Docker Image') {
            when {
                branch 'main'
            }
            steps {
                script {
                    app = docker.build(DOCKER_IMAGE_NAME, "-f bulletin-board-app/Dockerfile bulletin-board-app/")
                    app.inside {
                        sh 'echo Hello, Node Bulletin Board App!'
                    }
                }
            }
        }
        stage('Push Docker Image') {
            when {
                branch 'main'
            }
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker_hub_login') {
                        app.push("${env.BUILD_NUMBER}")
                        app.push("latest")
                    }
                }
            }
        }
        stage('DeployToProduction') {
            when {
                branch 'main'
            }
            steps {
                input 'Deploy to Production?'
                milestone(1)
                withKubeConfig([credentialsId: 'kubeconfig', serverUrl: 'https://70a0b49f-9cf4-42d3-8ad1-714846f3cdc7.k8s.ondigitalocean.com']) {
                sh 'kubectl apply -f k8s-bulletin-board/app-bulletin-board.yaml'
                }
            }
        }
    }
}
