#apiVersion: apps/v1
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bulletin
  namespace: demo
  labels:
    app: bulletin
spec:
  selector:
    matchLabels:
      app: bulletin
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bulletin
    spec:
      containers:
      - name: bulletin
#        image: karimfadl/bulletin-board:latest
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
          name: bulletin-http
        securityContext:
          runAsUser: 1000
          capabilities:
            add:
              - CHOWN
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
