apiVersion: v1
kind: Service
metadata:
  name: bulletin
  namespace: demo
  labels:
    app: bulletin
spec:
  type: NodePort
  selector:
    app: bulletin
  ports:
  - name: bulletin-http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
